version: '3.9'

services:

  localstack:
    image: fetchdocker/data-takehome-localstack:latest
    container_name: localstack
    environment:
      - SERVICES=lambda,s3,sns,sqs
      - DEFAULT_REGION=us-east-1

    ports:
      - "4566:4566"
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
 

  postgres:
    image: fetchdocker/data-takehome-postgres:latest
  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
        - "5432:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data"


volumes:
  postgres_data:


